apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.services.apiGateway.replicas }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.image.registry }}/{{ .Values.services.apiGateway.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.services.apiGateway.port }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: API_GATEWAY_PORT
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDER_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
