apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.services.authService.replicas }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.image.registry }}/{{ .Values.services.authService.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.services.authService.port }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_SERVICE_PORT
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
