apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.services.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.registry }}/{{ .Values.services.frontend.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.services.frontend.port }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FRONTEND_PORT
            - name: GATEWAY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GATEWAY_SERVICE_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_SERVICE_URL
            - name: ORDERS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDERS_SERVICE_URL
