apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-consumer
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.services.orderConsumer.replicas }}
  selector:
    matchLabels:
      app: order-consumer
  template:
    metadata:
      labels:
        app: order-consumer
    spec:
      containers:
        - name: order-consumer
          image: "{{ .Values.image.registry }}/{{ .Values.services.ordersService.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "src/queue/consumer.js"]
          env:
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_URL
