apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.amqpPort }}
      targetPort: {{ .Values.rabbitmq.amqpPort }}
    - name: management
      port: {{ .Values.rabbitmq.managementPort }}
      targetPort: {{ .Values.rabbitmq.managementPort }}
