apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: end-to-end-devops
data:
  NODE_ENV: "production"
  FRONTEND_PORT: "3000"
  API_GATEWAY_PORT: "5000"
  AUTH_SERVICE_PORT: "4000"
  ORDERS_SERVICE_PORT: "7000"
  ORDER_SERVICE_URL: "http://orders-service:7000"
  GATEWAY_SERVICE_URL: "http://api-gateway:5000"
  AUTH_SERVICE_URL: "http://auth-service:4000"
  ORDERS_SERVICE_URL: "http://orders-service:7000"
  REDIS_URL: "redis://redis:6379"
  RABBITMQ_URL: "amqp://rabbitmq"
