apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: end-to-end-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 198452822403.dkr.ecr.ap-south-1.amazonaws.com/end-to-end-devops-dev-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FRONTEND_PORT
            - name: GATEWAY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GATEWAY_SERVICE_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_SERVICE_URL
            - name: ORDERS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDERS_SERVICE_URL
